from .ApplicationView import ApplicationView
from .CollegeListView import CollegeListView
from .CompanyListView import CompanyListView
from .AnnouncementsListView import AnnouncementsListView
from .AppliedCompanysListView import AppliedCompnaysListView
from .CourseListView import CourseListView
from .HRContactModifyView import HRContactModifyView
from .SharedCompanyModifyView import SharedCompanyModifyView
from .SharedCompanyListView import SharedCompanyListView
from .HRListView import HRListView
from .MyHRListView import MyHRListView
from .SharedHRList import SharedHRList
from .StudentListView import StudentListView
from .AddAnnouncement import AddAnnouncement
from .HRDataUpdateView import HRDataUpdateView
from .DeleteAllSharedHRContactView import DeleteAllSharedHRContactView
from .HRAssignMeView import HRAssignMeView
from .HRCallHistoryView import HRCallHistoryView
from .TransferContactView import TransferContactView
from .UserLoginView import MyTokenObtainPairView
from .LogoutView import LogoutView
from .RegisterView import RegisterView
from .CollegeRegisterView import CollegeRegisterView
from .ResetPasswordView import ResetPasswordView
from .SaveDetailsView import SaveDetailsView
from .HRCallResponse import HRCallResponseView
from .DownloadAppliedStudentsListView import DownloadAppliedStudentsListView
from .StudentsApplicationView import StudentsApplicationView
from .AddApplicationView import AddApplicationView