# Generated by Django 5.0.2 on 2024-02-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_college_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_email', models.CharField(max_length=90)),
                ('company_contact', models.CharField(default='', max_length=20)),
                ('ctc', models.CharField(max_length=15)),
                ('college_visited', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=100)),
                ('is_company', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HR_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=20)),
                ('linkedin_id', models.CharField(max_length=70)),
            ],
        ),
    ]
