# Generated by Django 5.0.2 on 2024-03-01 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_merge_20240302_0028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company_contacts',
            new_name='Shared_Company',
        ),
        migrations.RenameModel(
            old_name='HR_contact',
            new_name='Shared_HR_contact',
        ),
    ]
