# Generated by Django 5.0.2 on 2024-03-29 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_merge_20240302_0028'),
        ('dashboard', '0004_userdetails_is_verified_and_more'),
    ]

    operations = [
    ]
