# Generated by Django 5.0.2 on 2024-03-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_userdetails_is_verified_and_more'),
        ('dashboard', '0005_rename_company_contacts_shared_company_and_more'),
    ]

    operations = [
    ]
