# Generated by Django 5.0.2 on 2024-04-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_merge_20240329_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='codechef_profile',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='codeforces_profile',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='github_profile',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='leetcode_profile',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='other_website_link',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='portfolio_link',
            field=models.URLField(null=True),
        ),
    ]
