# Generated by Django 5.0.2 on 2024-04-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Student'), (2, 'Helper'), (3, 'Coordinator'), (4, 'Officer'), (5, 'Admin 1'), (6, 'Admin 2')]),
        ),
    ]
