# Generated by Django 5.0.2 on 2024-04-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_announcement_created_announcement_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
