# Generated by Django 5.0.2 on 2024-04-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_application_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_fte',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_intern',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_ppo',
        ),
        migrations.AddField(
            model_name='application',
            name='is_fte',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='is_intern',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='is_ppo',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
