# Generated by Django 5.0.2 on 2024-04-17 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_company_is_fte_remove_company_is_intern_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrcontact',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.company'),
        ),
    ]
