# Generated by Django 5.0.2 on 2024-04-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_userdetails_codechef_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='codechef_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='codeforces_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='github_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='leetcode_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='other_website_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='portfolio_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
