# Generated by Django 5.0.2 on 2024-04-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_userdetails_codechef_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
