# Generated by Django 5.0.2 on 2024-04-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_application_last_date_alter_application_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='position',
            field=models.TextField(blank=True, null=True),
        ),
    ]
