# Generated by Django 5.0.2 on 2024-04-18 06:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_hrcontact_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrcontact',
            name='mobile',
        ),
        migrations.AddField(
            model_name='hrcontact',
            name='mobile_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='application',
            name='job_description',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
