# Generated by Django 5.0.2 on 2024-08-03 10:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_userprofile_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hrcontact',
            old_name='date_of_contact',
            new_name='last_date_of_contact',
        ),
        migrations.AddField(
            model_name='college',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrcontact',
            name='next_date_of_contact',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hrcontact',
            name='status',
            field=models.CharField(blank=True, choices=[('Do_Not_Contact', 'Do Not Contact'), ('Already_Contacted', 'Already Contacted'), ('To_Be_Contacted', 'To Be Contacted')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='callhistory',
            name='colour',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('green', 'Green'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('black', 'Black'), ('white', 'White'), ('gray', 'Gray'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('lime', 'Lime'), ('indigo', 'Indigo'), ('violet', 'Violet'), ('teal', 'Teal'), ('maroon', 'Maroon'), ('navy', 'Navy')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='subdomain',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hrcontact',
            name='mail_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254, null=True), blank=True, null=True, size=None),
        ),
    ]
