# Generated by Django 5.0.2 on 2024-08-05 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_rename_date_of_contact_hrcontact_last_date_of_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='college_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.collegecourse'),
        ),
    ]
