# Generated by Django 5.0.2 on 2024-08-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_announcement_college_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrcontact',
            name='mail_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hrcontact',
            name='mobile_numbers',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
