# Generated by Django 4.2.13 on 2024-08-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_application_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_hr_contact',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10),
        ),
        migrations.AlterField(
            model_name='hrcontact',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10),
        ),
        migrations.AlterField(
            model_name='shared_company',
            name='type',
            field=models.JSONField(default=dict),
        ),
    ]
