# Generated by Django 4.2.13 on 2024-08-12 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_shared_hr_contact_gender_alter_hrcontact_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shared_company',
            name='is_company',
        ),
    ]
